### ISSUE TITLE
Pull failed warning

### ISSUE THREAD

**Issue by drozzy** [denolehov/obsidian-git#61]
Setting both push and pull time to 1 minute I still get this occasionally (but nothing breaks):
![Screenshot from 2021-04-02 19-35-38](https://user-images.githubusercontent.com/140710/113461503-de87bc80-93ea-11eb-9058-16b7278f4e0d.png)

**Comment by Vinzent03** [comment]
Are you on the latest version?

**Comment by drozzy** [comment]
Yeah, I just installed it today.
It's odd it happens occasionally. Maybe it has something to do with pull&push and pull happening at the same time?

**Comment by Vinzent03** [comment]
What is the output of `git status` in the terminal?

**Comment by drozzy** [comment]
It's all clean. So clearly the pull/add/commit/push happens successfully.

**Comment by Vinzent03** [comment]
I have no problems with setting both pull and push to one minute. Now I get it. That's a normal git error message. You called `pull`, which was not able to merge fast-forward your changes, why git wants you to commit your changes. That happened, because the `push`command was called directly afterwards. That's no error with this plugin,
In generally you cannot pull when pulled files are not committed in your working directory.

**Comment by drozzy** [comment]
Um... I didn't call anything manually. My repo is pushed. 
But that's not even the issue for me. It's the pop up that's annoying. 

The plug-in still shows this error as a pop up even though I disabled notifications. It would be nice to disable this notification as well.

**Comment by Vinzent03** [comment]
The issue does still occur? Could you run  `git pull` manually from the terminal? Does it work without error?

This notification is handled as an error and not as an information, why the notifications is still shown.

**Comment by denolehov** [comment]
@drozzy please make sure that your files are backed up by other means rather than via git, and run `git reset --hard` and then `git pull` from the command line. Making your repository "clean" should resolve this issue.

**Comment by drozzy** [comment]
Yes, I ensured that my `git pull` is clean and I did `git reset --hard` as well. I am certain my repository is clean. Yet it still happens.

I observed that this happens if I am typing something continuously, and the "obsidian git" plugin is triggered in the middle of me typing.

**Comment by Vinzent03** [comment]
Do you have only auto pull enabled or auto push too? And the remote repo had no changes since the last push from Obsidian? Because I think this error can just be related to changes from the remote.

**Comment by a-trost** [comment]
Hey @Vinzent03 I have both enabled at 3 minute intervals.
Here are my settings:
![image](https://user-images.githubusercontent.com/19617280/114395032-e7eef280-9b69-11eb-86e2-1918cf35bf82.png)

Nothing changed on the remote repo.
I'm guessing there's something weird with the combination of Push+Pull happening at the same time plus the "Pull changes before push" firing all at once. Just a hunch though.

**Comment by Vinzent03** [comment]
I can reproduce. Working on it now.

**Comment by Vinzent03** [comment]
I hope the new release fixes the issue. Added a promise queue so that the commands are not executed simultaneously.
