### ISSUE TITLE
[Bug]: buffer error on iOS

### ISSUE THREAD

**Issue by mpapamanz** [denolehov/obsidian-git#659]
### Describe the bug

Since i added a pdf/blob in my git repository i am getting "buffer error".
The directory with the pdf doesn't pull (but some others do)
Pushes totally fail

Interestingly i have another directory with a much bigger PDF that just works

### Steps to reproduce

* Add a pdf in a directory
* Fetch/commit
* Get buffer error

### Expected Behavior

Not getting buffer error 🙂

### Operating system

iOS

### Installation Method

None

### Plugin version

2.22

**Comment by philipcristiano** [comment]
I’ve been running into this as well when adding a ~5MB jpg file.

**Comment by RDust4** [comment]
I have the exact same problem, pushing just throws a "buffer error".

**Comment by mpapamanz** [comment]
I did a bit of experiments, in the following the finding:
1. Deleting/adding to gitignore the largest fine (~9MB) everything works perfectly
2. Adding the big file on the mobile, committing works. Push doesn't (and Pull doesn't either that triggered me filing this bug)
3. Once the large file is committed, there is no way back (I guess it is because the file stays in the local log and needs to be pushed)

(2) makes me think that the issue is with network rather than with the local client.
(3) makes me thing that what @RDust4 is experiencing may be due to a huge log (for some reason)

Happy to do more experiments and/or grabbing logs (I have to figure out how though :)

**Comment by RDust4** [comment]
I had a plugin installed named obsidian-likzjax, which does not work on mobile (it threw a "plugin failed to load" on startup).
After uninstalling the plugin, everything now works as normal.
As soon as thr main.js of that plugin was in the commit, it failed to push.

**Comment by anibaldeboni** [comment]
I have the same bug on iOS. At first it was working fine but after some time using the feature the error begun to appear.
I don't have any large files, only small text files. I have tried to disable all extension except `obsdian-git`, reinstall the app, but nothing worked.

**Comment by RDust4** [comment]
> I don't have any large files, only small text files. I have tried to disable all extension except `obsdian-git`, reinstall the app, but nothing worked.

Disabling extensions doesn't do anything because the plugins themselves are backed up either way.
You would have to uninstall extensions for that to work.

Personally, I have fixed my problem by adding a .gitignore for plugins.
This backs up everything except plugins and their settings, thus resolving the problem.

The exact steps I took:

On desktop:
1. add the ".gitignore" file to the vault root
2. add "/.obsidian/plugins" to the gitignore file (I used notepad -> save under -> go to your vault root)
3. backup (commit all changes and push) the vault
4. check on git if the .obsidian/plugins folder is gone in the latest commit

Then on mobile:
5. delete old vault & create new empty vault
6. install obsidian-git, enable, and add git credentials
7. clone your vault
8. install all your plugins manually
9. change something and test if commit&push works

Hope that helps!

**Comment by anibaldeboni** [comment]
> I had a plugin installed named obsidian-likzjax, which does not work on mobile (it threw a "plugin failed to load" on startup). As soon as thr main.js of that plugin was in the commit, it failed to push. After then uninstalling the plugin, everything works as normal.



> > I don't have any large files, only small text files. I have tried to disable all extension except `obsdian-git`, reinstall the app, but nothing worked.
> 
> Disabling extensions doesn't do anything because the plugins themselves are backed up either way. You would have to uninstall extensions for that to work.
> 
> Personally, I have fixed my problem by adding a .gitignore for plugins. This backs up everything except plugins and their settings, thus resolving the problem.
> 
> The exact steps I took:
> 
> On desktop:
> 
>     1. add the ".gitignore" file to the vault root
> 
>     2. add "/.obsidian/plugins" to the gitignore file (I used notepad -> save under -> go to your vault root)
> 
>     3. backup (commit all changes and push) the vault
> 
>     4. check on git if the .obsidian/plugins folder is gone in the latest commit
> 
> 
> Then on mobile: 5. delete old vault & create new empty vault 6. install obsidian-git, enable, and add git credentials 7. clone your vault 8. install all your plugins manually 9. change something and test if commit&push works
> 
> Hope that helps!

Unfortunately it didn't work. I did everything you mentioned (including reinstalling obsidian and only using `obsidian-git` plugin) but the `buffer error` is still happening

**Comment by RDust4** [comment]
Could you try the same thing again, but add the whole .obsidian folder to .gitignore?
I think the problem lies somewhere in there.

**Comment by zed106** [comment]
I have faced the same issue. Here is how I solve it:
1. Delete the directory of the old vault in iphone: My Iphone->Obsidian->XXX(my vault name)
2. Use a new git client to clone the repository of my vault. I use PolyGit(I think it doesn't matter, I just want to clone the repository to my iphone).
3. Find the repository directory in "My Iphone->PolyGit->XXX", and move it to "My Iphone->Obsidian"
4. open Obsidian on iphone

The old (WRONG) way to create the vault on my iphone was like this:
1. git clone the reposity XXX (on windows)
2. zip XXX to XXX.zip  (on windows)
3. send XXX.zip to my iphone, and place it under "My Iphone->Obsidian".
4. Open Obsidian in iphone
Then it pops "buffer error" when "git push". I use a git client app on my iphone to open the XXX, and it also pops errors. So I assume something went wrong when I copy files from windows to my iphone. Then I use git client clone the repository directly on my iphone, then move it to Obsidian dir. It works well。

**Comment by truppelito** [comment]
> Could you try the same thing again, but add the whole .obsidian folder to .gitignore? I think the problem lies somewhere in there.

I’ve just encountered the same issue. I don’t have large files in my vault. And I also have had, since the beginning, the entire .obsidian folder in my .gitignore. The problem must be lying somewhere else.

**Comment by 4ku** [comment]
Have the same issue

**Comment by atharvanvaidya** [comment]
I encountered the issue of `buffer error` on mobile device when ~10 files were pushed from the laptop and pulled on the mobile device. With 2-3 files, everything was working correctly - pushing and pulling from the mobile device. However, when the count of files were increased, this error started showing up.

**Comment by MgTheProgrammer** [comment]
I also encountered the buffer error today.  
  
To summarize don't be me. **Please update the plugin**.   

Even though I think that simply updating the plugin could have solved the problem on it's own as the actions I preformed before I finally updated it shouldn't actually be connected to the resolution of the problem, figured that sharing what I did before the update can't  be of harm:  

Firstly I wanted to know if the problem is with the plugin or something else with running git on iPhone, so I downloaded [ish](https://github.com/ish-app/ish) which allowed me to download git in a terminal.  
  
I mounted the Obsidian folder into the ish filesystem, and recloned my repo with regular terminal git.   
After cloning I tried doing both `git status` and `git add` and they both hang up and required me to restart ish, which led me to [this thread](https://github.com/ish-app/ish/issues/1640), surely enough `git config --global pack.threads "1" ` seemed to do the trick and allow me to use git as I would on any regular machine.    
  
When I Opened the new Vault I thought I might give the obsidian-git plugin another try incase that for some reason something was resolved.   
But as the vault was new I needed to reinstall the plugin, this is when I found out that the plugin was updated and the command is no longer called backup.  Tried running the new sync command and it worked as I expected.

**Comment by keisukeoyamada** [comment]
@everyone
@mpapamanz 
I encountered the buffer error today.
Maybe when files up to 1000 changed in local repository, ios vault throw buffer error(<<It's just a guess.).

I do bellow and resolve error.
* do below on your ios devise.

1. [iPhone] Obsidian, Installation of Working Copy App
	- [Obsidian](https://obsidian.md/mobile)
	- [Working Copy](https://apps.apple.com/jp/app/working-copy-git-client/id896694807)
2. [iPhone] Downloading Memos Locally via Working Copy
	1. Clone the repository created on GitHub in the Working Copy app.
    2. Select the + icon in Repositories > Clone repository.
    3. Sign In to GitHub and execute the clone (clone via https).
    4. Save the cloned files to the Obsidian folder on your iPhone.
    5. Select the icon below > Save to Files, and select the Obsidian folder in This iPhone.
3. A zip file will be saved, so tap the zip file from the Files app to unzip it.
4.  [iPhone] Confirmation in Obsidian App
	1. Check the home screen of the Obsidian app, and the unzipped folder should be displayed in the vault list.
	* If you have Obsidian Git installed and enabled in advance, the warning will not be displayed.
5. Automatic push and pull are now possible.

**Comment by massivedynamics** [comment]
After trying many below does the trick for me.

Ignore local obsidian specific files. Basically every file/folder you see in changed list but not interested to version control. 

.gitignore
```
.obsidian/workspace*
.obsidian/plugins/*/data*
.obsidian/plugins/*/historie*
```

Windows/Linux, CR + LF bytes are replaced with LF bytes. This was causing problems. I have md, pdf, jpg and png files. Luckily isomorphic-git respects .git files/folder. 

.gitattributes
```
* text=auto
```
